from enum import Enum


class FileStatus(str, Enum):
    UPLOADING_TO_S3 = "UPLOADING_TO_S3"
    GENERATING_EMBEDDINGS = "GENERATING_EMBEDDINGS"
    EMBEDDINGS_GENERATED = "EMBEDDINGS_GENERATED"
    ERROR_OCCURRED = "ERROR_OCCURRED"
    FAILED = "FAILED"
    SUCCESS = "SUCCESS"
